collection = "Luo Tianyi, Yuezheng Ling/洛天依_乐正绫"
video_title = "【FULL ver. new MV】Luo Tianyi_Yuezheng Ling 洛天依_乐正绫 - Millennium of Frost and Snow 霜雪千年【COP _ 霜雪千年灯】"

[song-titles]
en = "Millennium of Frost and Snow"
zh = "霜雪千年"
