markers = [
  "cre",
  "ttl",
  "txt",
  "LTY",
  "lty",
  "YZL",
  "yzl",
  "Y+L",
]

credits = ["cre"]

[voices]
LTY = { vi = "Lạc Thiên Y", zh = "洛天依" }
lty = { vi = "Lạc Thiên Y (thoại)", zh = "洛天依（念白）" }
YZL = { vi = "Nhạc Chính Lăng", zh = "乐正绫" }
yzl = { vi = "Nhạc Chính Lăng (thoại)", zh = "乐正绫（念白）" }
"Y+L" = { vi = "Lạc Thiên Y & Nhạc Chính Lăng", zh = "洛天依 & 乐正绫" }

[classes]
ttl = "title"
txt = "expo"

[styles.ttl]
color = "#FFD966"
bold = true

[styles.txt]
color = "#CCCCCC"
italic = true

[styles.LTY]
color = "#66CCFF"

[styles.lty]
color = "#66CCFF"
italic = true

[styles.YZL]
color = "#EE0000"

[styles.yzl]
color = "#EE0000"
italic = true

[styles."Y+L"]
color = "#9966CC"
