[credit-roles]
zh = ["作词", "编曲", "VSINGER", "笛子", "作曲", "演唱", "调校", "制作人", "Ｖ家曲绘", "美术", "PV", "鸣谢素材"]
vi = ["Tác từ", "Biên khúc", "VSINGER", "Sáo", "Tác khúc", "Trình bày", "Điều giáo", "Sản xuất", "Hình ảnh", "Mỹ thuật", "PV", "Cảm ơn"]

[credit-names]
zh = ["雨観", "雨观", "洛天依X楽正绫", "再也不上课", "雨観X溪里", "鬼面P", "Vsinger团队", "碎夊", "超级水水", "山晚樵渔"]
vi = ["Luo Tianyi X Yuezheng Ling"]

[songstress-names.zh]
LTY = "洛天依"
lty = "洛天依（念白）"
YZL = "乐正绫"
yzl = "乐正绫（念白）"
"Y+L" = "洛天依 & 乐正绫"

[songstress-names.vi]
LTY = "Lạc Thiên Y"
lty = "Lạc Thiên Y (thoại)"
YZL = "Nhạc Chính Lăng"
yzl = "Nhạc Chính Lăng (thoại)"
"Y+L" = "Lạc Thiên Y & Nhạc Chính Lăng"

[song-titles]
vi = "Thanh Đàn Ký"
zh = "青檀記"
