collection = "Luo Tianyi, Yuezheng Ling, YANHE/洛天依"
video-title = "[Official Song] Luo Tianyi 洛天依 - Thousand Lights Painting 千灯绘【2026冰火盛典新春季】 [sb1Nx__901M]"

[song-titles]
en = "Thousand Lights Painting"
vi = "Thiên Đăng Hội"
zh = "千灯绘"
