[[credit-roles]]
zh = "演唱"
vi = "Trình bày"

[[credit-roles]]
zh = "作曲"
vi = "Soạn nhạc"

[[credit-roles]]
zh = "作词"
vi = "Viết lời"

[[credit-roles]]
zh = "编曲"
vi = "Phối khí"

[[credit-roles]]
zh = "企划"
vi = "Kế hoạch"

[[credit-roles]]
zh = "制作人"
vi = "Nhà sản xuất"

[[credit-roles]]
zh = "调校"
vi = "Căn chỉnh giọng hát"

[[credit-roles]]
zh = "和声编写"
vi = "Viết hòa thanh"

[[credit-roles]]
zh = "混音"
vi = "Hòa âm"

[[credit-roles]]
zh = "美术"
vi = "Mỹ thuật"

[[credit-roles]]
zh = "视频"
vi = "Video"

[[credit-roles]]
zh = "素材鸣谢"
vi = "Tư liệu tham chiếu"

[[credit-names]]
zh = "洛天依"
vi = "Luo Tianyi"

[[credit-names]]
zh = "乐正绫"
vi = "Yuezheng Ling"

[[credit-names]]
zh = "雨观"

[[credit-names]]
zh = "三世"

[[credit-names]]
zh = "鬼面Ｐ"

[[credit-names]]
zh = "一勺酸橙汁"

[[credit-names]]
zh = "Ａ影羌"

[[credit-names]]
zh = "璇玑坊Studio"

[[credit-names]]
zh = "废画"

[[credit-names]]
zh = "良月十八"

[[credit-names]]
zh = "无声诗"

[[credit-names]]
zh = "山晚樵渔"

[[credit-names]]
zh = "今日晴"

[[credit-names]]
zh = "九镜"

[speaker-names.zh]
LRC = "洛天依 X 乐正绫"

[speaker-names.vi]
LRC = "Luo Tianyi X Yuezheng Ling"
