[credit-roles]
zh = ["演唱", "作曲", "作词", "编曲", "企划", "制作人", "调校", "和声编写", "混音", "美术", "视频", "素材鸣谢"]
vi = ["Trình bày", "Soạn nhạc", "Viết lời", "Phối khí", "Kế hoạch", "Nhà sản xuất", "Căn chỉnh giọng hát", "Viết hòa thanh", "Hòa âm", "Mỹ thuật", "Video", "Tư liệu tham chiếu"]

[credit-names]
zh = ["洛天依", "乐正绫", "雨观", "三世", "鬼面Ｐ", "一勺酸橙汁", "Ａ影羌", "璇玑坊Studio", "废画", "良月十八", "无声诗", "山晚樵渔", "今日晴", "九镜"]
vi = ["Luo Tianyi", "Yuezheng Ling"]

[song-titles]
vi = "Trường Ca Nhất Khứ Giang Hồ Viễn"
zh = "長歌一去江湖遠"
