name: Test

on:
  - push
  - pull_request

jobs:
  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        shell: bash
        run: |
          installer=$(mktemp -d)/install-rustup
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > $installer
          bash $installer --default-toolchain $(cat rust-toolchain) --component rustfmt -y

      - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Cache
        uses: actions/cache@v5
        timeout-minutes: 2
        continue-on-error: true
        with:
          path: |
            ~/.cargo
            target
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-

      - name: Install Rust
        shell: bash
        run: |
          installer=$(mktemp -d)/install-rustup
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > $installer
          bash $installer --default-toolchain $(cat rust-toolchain) --component clippy -y

      - run: cargo clippy -- -D warnings

      - name: Clean workspace artifacts before cache
        if: always()
        continue-on-error: true
        shell: bash
        run: cargo clean --workspace

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Cache
        uses: actions/cache@v5
        timeout-minutes: 2
        continue-on-error: true
        with:
          path: |
            ~/.cargo
            target
          key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}-

      - name: Install Rust
        shell: bash
        run: |
          installer=$(mktemp -d)/install-rustup
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > $installer
          bash $installer --default-toolchain $(cat rust-toolchain) -y

      - run: cargo test

      - name: Clean workspace artifacts before cache
        if: always()
        continue-on-error: true
        shell: bash
        run: cargo clean --workspace
